### ISSUE TITLE
"Previous/Next Train" toast lags significantly behind user switches between trains

### ISSUE THREAD

**Issue by krystynneisess** [nickfong/CS160-Collaboration#11]
Not sure to what extent we can influence this delay, but worth mentioning just in case there is something we can do something about it.

[integration-bart+mobile]

**Comment by krystynneisess** [comment]
@DaiweiLiu was this addressed in commit `1833706` ("optimized the drawing method of PacingView")?  If so, please confirm!

**Comment by packsun** [comment]
http://stackoverflow.com/questions/3775074/set-toast-appear-length/9715422#9715422

try this solution

**Comment by nickfong** [comment]
Pinging @DaiweiLiu

**Comment by DaiweiLiu** [comment]
Yes this should be fixed by the optimization commit (1833706)
