### ISSUE TITLE
Potential wear pacing display issues

### ISSUE THREAD

**Issue by krystynneisess** [nickfong/CS160-Collaboration#18]
Experienced whilst filming yesterday, but as of yet not reproducible:  

- Occasionally, the Display Activity (if I recall correctly) would leak a ServiceConnection.
- The person's arrival time displayed outlandishly large numbers (in the thousands).
- When a more reasonable value was hard-coded in, the background-color-changing control statements no longer worked.

**Comment by DaiweiLiu** [comment]
The second problem should be fixed by adding "( )" around fetchInterval / 1000 in NavActivity.java on the mobile side

**Comment by krystynneisess** [comment]
@DaiweiLiu:  any ideas/updates regarding the first or third issues?
@packsun:  please look into the second issue/push changes if a fix has been done.

**Comment by packsun** [comment]
second issue is fixed with a095e4f

**Comment by nickfong** [comment]
This hasn't been reproduced in a few days, so closing this ~~ticket~~ issue as the issue has so far been "not reproducible"
