### ISSUE TITLE
BART API data not integrated with postSelection activity.

### ISSUE THREAD

**Issue by krystynneisess** [nickfong/CS160-Collaboration#19]
Populate the following with real BART data;
- Trip duration
- Fare (one-way + round-trip)
- Next train (type, arrival time)

@michaelyxu rebase off of branch `integration-bart+mobile`

**Comment by nickfong** [comment]
Everything but the trip duration has been implemented.

**Comment by nickfong** [comment]
Trip duration has been changed to train departure time since the trip duration isn't pulled from the BART API.  Closing.
