### ISSUE TITLE
BART API data not integrated with pacing UI.

### ISSUE THREAD

**Issue by krystynneisess** [nickfong/CS160-Collaboration#21]
Send train arrival times to wear side's pacing UI.  

@packsun  I'm guessing this is under your purview?  (If not, reassign as necessary.)

[integration-bart+mobile]

**Comment by packsun** [comment]
need some help from @nickfong regarding how the arrival times are being pulled from the API

**Comment by nickfong** [comment]
Ping me on Slack whenever you want to work on this

**Comment by nickfong** [comment]
The current implementation works but is suboptimal.  Only one train route's
ETAs are used (so for example if the user can catch an Fremont or a
Millbrae train to get to MacArthur from Downtown Berkeley, only Fremont
train ETAs will be shown if the Fremont train is coming first, or only
Millbrae train ETAs will be shown.  Will attempt to fix shortly, assuming
nothing more urgent comes up.

**Comment by nickfong** [comment]
Attempted fix in 243081c.  Assigning back to @packsun to integrate into `postSelection.java`

Two relevant method calls are:
`String getNextDepartureTimes(Trip)`
and
`String getNextDepartureDestination(Trip)`

**Comment by nickfong** [comment]
This change has been implemented and runs on hardware.  Closing
