### ISSUE TITLE
Wear does not observe turn-by-turn navigation switch value.

### ISSUE THREAD

**Issue by krystynneisess** [nickfong/CS160-Collaboration#22]
That is, regardless of whether the post-selection page's Turn-by-Turn Navigation switch is on or off, navigation instructions are still accessible to the user.  (I'm guessing this is because the navigation instructions are currently hard-coded on the wear side?)  

Navigation instructions are stored into a global ArrayList navInstructions in NavActivity.java.  Mobile side takes care of reading the toggle switch value; wear must simply interpret the navInstructions object that is to be passed along.  

If navInstructions == null, it means no instructions were fetched, indicating the toggle switch was off (or that retrieving instructions was unsuccessful--in which case, uh, the user should also not receive instructions).  

If navInstructions != null, then instructions were fetched, indicating the toggle was on, and that the user should in fact have access to instructions.

@packsun + @DaiweiLiu Please look into this!

[integration-bart+mobile]

**Comment by packsun** [comment]
the toggle works as of f97a06c, but the instructions themselves are still hard-coded on the wear. navInstructions in mobile aren't being sent to the watch yet
