### ISSUE TITLE
Watch Should Vibrate Upon Screen Color Change

### ISSUE THREAD

**Issue by nickfong** [nickfong/CS160-Collaboration#26]
Didn't get a chance to open an issue on this yesterday.  Assigning to @DaiweiLiu who is currently implementing a solution.

**Comment by krystynneisess** [comment]
While commit '94fe385` message says it addresses it, currently on hardware the watch instead just periodically vibrates every 3 seconds or so, independent of background color changes.

**Comment by nickfong** [comment]
@DaiweiLiu attempted a fix in 9365e7b; assigning to @krystynneisess for on-hardware testing.

**Comment by nickfong** [comment]
Watch doesn't vibrate on color change again.  Assigned back to @DaiweiLiu for further troubleshooting.

**Comment by nickfong** [comment]
@DaiweiLiu attempted a fix in 869522d.  Assigning back to @krystynneisess for on-HW testing.

**Comment by nickfong** [comment]
Confirmed working on HW.  Closing.
