### ISSUE TITLE
App crashes at postSelection when no trains available. 

### ISSUE THREAD

**Issue by krystynneisess** [nickfong/CS160-Collaboration#32]
Or so is the best guess at why the app crashes exclusively upon launching postSelection.  

Rationale:
The station lists are still populated, as are the maps and the fare information in the custom markers.  These, I've noticed, all rely on static information, not dependent on real-time data from trains.  As the only real-time data (currently implemented) in use is fetching the next trains, it is possible that an absence of trains may be the cause for this crash.  Unfortunately, the logcat doesn't display conspicuous error messages describing the crash behavior.

If debugging during the day (when there are trains), consider attempting to reproduce the bug by hardcoding an absence of trains.

[integration-bart+mobile]

**Comment by nickfong** [comment]
This should be fixed in a commit from this morning that I'm currently too lazy to look up the hash of.

**Comment by krystynneisess** [comment]
Confirmed fix, as of commit `fdb17ba` Appropriate text supplants train arrival time and the like.
