### ISSUE TITLE
Fix getDistance Method

### ISSUE THREAD

**Issue by nickfong** [nickfong/CS160-Collaboration#34]
Currently, `getDistance` gives the as-the-crow-flies distance between the user and the BART station.  Unfortunately, we don't list grappling hooks as a system (or rather user?) requirement for running our app, so users can't scale the sides of buildings.  

Jokes aside, this method should be updated to use a Google Maps API call to get the walking distance between the user's current location and the BART station to give a more accurate walking distance from the user's location to the station.  

Assigning to @packsun

**Comment by nickfong** [comment]
@krystynneisess and I tested this method and it's giving a distance of 158.304... (units unknown) from Jacobs to Downtown Berkeley BART.

**Comment by packsun** [comment]
While the Google Maps API is definitely the best solution, I don't think it's necessary for our submission. I believe that chances of things going wrong will be higher if we're making a GET request every 5 seconds, so I'd rather have our user ETA be a bit off than have something break completely. I'll use Android's built-in Location methods which should be more stable than the methods I wrote, but still give the as-the-crow-flies distance.

**Comment by packsun** [comment]
modified to use Location.distanceTo as described above in f97a06c
